    # .github/workflows/deploy.yml
    name: Deploy Next.js to GitHub Pages

    on:
      push:
        branches:
          - main # Trigger on pushes to the main branch

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20' # Or your preferred Node.js version

          - name: Install dependencies
            run: npm install

          - name: Build Next.js app
            run: npm run build # This will run 'next build && next export' if configured in package.json

          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v4
            with:
              github_token: ${{ secrets.SECRET_PAT }}
              publish_dir: ./out # Directory containing your static Next.js output
